format_version: 10
pipelines:
  build:
    group: Test
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-8a2829d:
        git: https://github.com/shakirshakiel/gocd-environments.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          build:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - build
                command: echo
                run_if: passed
